name: Deploy to S3 using AWS CLI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: amazon/aws-cli:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to S3
      run: aws s3 sync . s3://s3-directory-listing/ --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
